# Generated by Django 4.2 on 2023-05-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='phone'),
            preserve_default=False,
        ),
    ]
