# Generated by Django 4.2 on 2023-06-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_adminuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='NormalUser',
        ),
    ]
